language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-source
  - travis_retry composer require satooshi/php-coveralls:dev-master --prefer-source

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
