language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
